### ISSUE TITLE
Crash with proposed json config

### ISSUE THREAD

**Issue by federico-galli** [jaimindp/Twitter_Activated_Crypto_Trading_Bot#1]
Hi, I am testing your software (successfully with self tweet)
I noticed that python twitter_binance.py crashes if specified (with values or not) the kraken line. 
The keys.json with twitter_binance.py works with this format

`{
    "twitter_keys":{
        "consumer_key":"xxx",
        "consumer_secret":"xxx",
        "access_token_key":"xxx",
        "access_token_secret":"xxx"
    },
    "binance_keys":{
        "api_key":"xxx",
        "secret_key":"xxx"
    }
}
`

**Comment by jaimindp** [comment]
Hi Federico,

What is the error message you are receiving, you should be able to use the
keys.json file without kraken (and with binance) or without binance (and
with kraken) keys?

Are you trading with Kraken or Binance?

If you are trading with Binance please use 'python twitter_binance.py'

If you are trading with Kraken please use 'python twitter_kraken.py' (This
one I have not tested for a while and have received notice that the api was
down today from Kraken support on twitter)

Kind regards,
Jaimin

**Comment by federico-galli** [comment]
Hi, I am trading with binance, I have successfully self tested doge/btc buy sell in a 30s timeline. 
If I use this format for the json

 `{ "twitter_keys":{ "consumer_key":"xxx", "consumer_secret":"xxx", "access_token_key":"xxx", "access_token_secret":"xxx" }, "binance_keys":{ "api_key":"xxx", "secret_key":"xxx" } } ` 

it works correctly. If I use the one one on the readme, with the "kraken" like like this 
`{
    "twitter_keys":{
        "consumer_key":"XXXXXXXXXXXXXXXXXXXX",
        "consumer_secret":"XXXXXXXXXXXXXXXXXXXX",
        "access_token_key":"XXXXXXXXXXXXXXXXXXXX",
        "access_token_secret":"XXXXXXXXXXXXXXXXXXXX"
    },
    "binance_keys":{
        "api_key":"XXXXXXXXXXXXXXXXXXXX",
        "secret_key":"XXXXXXXXXXXXXXXXXXXX"
    },
    "kraken_keys":{XXXXXX}
}`

i first get an escape error because it says that kraken_keys needs "somekey" (correcty I think) and if I fill the value it gives 

`Traceback (most recent call last):
  File "twitter_binance.py", line 59, in <module>
    api_keys = json.loads(f.read())
  File "/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 12 column 23 (char 545)
`

I am not trading with kraken, but if someone trade with kraken AND binance, should have 2 separate config files?
I do understand it's a works in progres, I am just curious. Thanks in advance.

**Comment by jaimindp** [comment]
Ah I see if you put double quotes around the "kraken_keys":{"XXXXXXX"} it
should work. It's just an incorrectly formatted json file

**Comment by federico-galli** [comment]
Not exactly, without the double quote I get this error

`json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 12 column 20 (char 542)`

and with the double quotes, like  "kraken_keys":{"XXXXXXX"} i get this other error

`json.decoder.JSONDecodeError: Expecting ':' delimiter: line 12 column 28 (char 550)`


but it just works if I fully remove the kraken line.

**Comment by jaimindp** [comment]
Yeah removing , "kraken_keys" {} should work too. I was just being lazy
with the formatting

**Comment by federico-galli** [comment]
Thanks :-)
I hope you will implement the "new listed coin feature" :-)
Now I hope to test the real thing soon. Such Moon Much Doge!

**Comment by jaimindp** [comment]
No problem.
