### ISSUE TITLE
Fail at tweet collector

### ISSUE THREAD

**Issue by federico-galli** [jaimindp/Twitter_Activated_Crypto_Trading_Bot#3]
I've got two errors during the last days (last git fetch)
While waiting for tweet, running for 2-3 days

one session

[{'message': 'Internal error', 'code': 131}] 
Failed at tweet collector

another session

[{'message': 'Over capacity', 'code': 130}] 
Temporarilty failed at tweet collector

**Comment by jaimindp** [comment]
That means that the Twitter API did not work on that specific  query, so on
2 seconds out of the possible 2-3 days it failed to query the tweet.

Nothing to worry about as long as this message does not repeat once every
second, it quickly resumes querying tweets.

**Comment by jaimindp** [comment]
If you are still getting this error and it has got worse, the same has happened to me. It seems that requesting @elonmusk twitter timeline has been overloaded by a number of bots and now produces no/erroneous results. I have updated the code with a Tweepy streamer which is slower but should be more robust

**Comment by federico-galli** [comment]
Yes I had a lot of warning during the last hours. I am going to fetch the new code. thanks for your work
