### ISSUE TITLE
ModuleNotFoundError: No module named 'binance_futures_api'

### ISSUE THREAD

**Issue by ghost** [jaimindp/Twitter_Activated_Crypto_Trading_Bot#4]
New error, ive tried pip install binance_futures_api, but theres no module. 

C:\Users\Adobe\Desktop\Twitter_Activated_Crypto_Trading_Bot-main>python twitter_kraken.py
Traceback (most recent call last):
  File "twitter_kraken.py", line 6, in <module>
    from stream import *
  File "C:\Users\Adobe\Desktop\Twitter_Activated_Crypto_Trading_Bot-main\stream.py", line 9, in <module>
    from binance_futures_api import *
ModuleNotFoundError: No module named 'binance_futures_api'

**Comment by ghost** [comment]
Ive deleted "binance_futures_api import *" from query.py, stream.py and is working again. Im guessing because im using Kraken.

**Comment by jaimindp** [comment]
Thanks I've pushed the change
