### ISSUE TITLE
Plans to support other exchanges in the future

### ISSUE THREAD

**Issue by daiisi** [jaimindp/Twitter_Activated_Crypto_Trading_Bot#5]
Hi,I am currently using this program, and I would like to ask you one question: this program currently supports binance and kraken, but do you have any plans to support FTX?

**Comment by jaimindp** [comment]
Hi, I actually don't have any plans to include other exchanges at the moment. I started with Kraken and moved to Binance as these are the two I used. If FTX is supported by ccxt, the function calls should be interchangeable (if implemented) for any exchange api supported.
